nodeLinker: node-modules

npmRegistryServer: "https://repo.mci.dev/artifactory/api/npm/npm/"

npmScopes:
  my-company:
    npmAlwaysAuth: true
    npmAuthIdent: "$CICD_REPO_USER:$CICD_REPO_PASS"
    npmRegistryServer: "https://repo.mci.dev/artifactory/api/npm/npm/"
